# Generated by Django 4.2.27 on 2026-02-08 22:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt_text', models.TextField()),
                ('task_type', models.CharField(choices=[('writing', 'Writing'), ('speaking', 'Speaking')], default='writing', max_length=20)),
                ('mode', models.CharField(choices=[('independent', 'Independent'), ('integrated', 'Integrated')], default='independent', max_length=20)),
                ('resource_url', models.CharField(blank=True, max_length=500, null=True)),
                ('difficulty', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('evaluation_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(help_text='Reference to Core User UUID')),
                ('task_type', models.CharField(choices=[('writing', 'Writing'), ('speaking', 'Speaking')], default='writing', max_length=20)),
                ('submitted_text', models.TextField(blank=True, null=True)),
                ('audio_path', models.CharField(blank=True, max_length=500, null=True)),
                ('overall_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('ai_feedback', models.TextField(blank=True, null=True)),
                ('transcript_text', models.TextField(blank=True, null=True)),
                ('rubric_version_id', models.CharField(blank=True, help_text='Track rubric version for scoring consistency', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='team7.question')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DetailedScore',
            fields=[
                ('score_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criterion', models.CharField(max_length=50)),
                ('score_value', models.DecimalField(decimal_places=1, max_digits=3)),
                ('comment', models.TextField(blank=True, null=True)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_scores', to='team7.evaluation')),
            ],
        ),
        migrations.CreateModel(
            name='APILog',
            fields=[
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(blank=True, help_text='Reference to User UUID (null for unauthenticated)', null=True)),
                ('endpoint', models.CharField(help_text='API endpoint path', max_length=200)),
                ('method', models.CharField(default='GET', help_text='HTTP method', max_length=10)),
                ('status_code', models.IntegerField(help_text='HTTP response status code')),
                ('latency_ms', models.IntegerField(help_text='Request processing time in milliseconds')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('error_message', models.TextField(blank=True, help_text='Error details if status >= 400', null=True)),
                ('request_size', models.IntegerField(blank=True, help_text='Request body size in bytes', null=True)),
                ('response_size', models.IntegerField(blank=True, help_text='Response body size in bytes', null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['endpoint', '-timestamp'], name='team7_apilo_endpoin_3c240d_idx'), models.Index(fields=['status_code', '-timestamp'], name='team7_apilo_status__c2f34f_idx'), models.Index(fields=['user_id', '-timestamp'], name='team7_apilo_user_id_648d6c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['user_id', '-created_at'], name='team7_evalu_user_id_dde41e_idx'),
        ),
    ]
