# Generated by Django 4.2.27 on 2026-02-11 19:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('team7', '0002_exam_question_changes'),
    ]

    operations = [
        migrations.CreateModel(
            name='APILog',
            fields=[
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(blank=True, help_text='Reference to User UUID (null for unauthenticated)', null=True)),
                ('endpoint', models.CharField(help_text='API endpoint path', max_length=200)),
                ('method', models.CharField(default='GET', help_text='HTTP method', max_length=10)),
                ('status_code', models.IntegerField(help_text='HTTP response status code')),
                ('latency_ms', models.IntegerField(help_text='Request processing time in milliseconds')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('error_message', models.TextField(blank=True, help_text='Error details if status >= 400', null=True)),
                ('request_size', models.IntegerField(blank=True, help_text='Request body size in bytes', null=True)),
                ('response_size', models.IntegerField(blank=True, help_text='Response body size in bytes', null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['endpoint', '-timestamp'], name='team7_apilo_endpoin_3c240d_idx'), models.Index(fields=['status_code', '-timestamp'], name='team7_apilo_status__c2f34f_idx'), models.Index(fields=['user_id', '-timestamp'], name='team7_apilo_user_id_648d6c_idx')],
            },
        ),
    ]
