# Generated by Django 4.2.27 on 2026-02-10 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('topic', models.CharField(choices=[('biology', 'Biology'), ('history', 'History'), ('astronomy', 'Astronomy'), ('geology', 'Geology'), ('anthropology', 'Anthropology')], max_length=50)),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('text_length', models.IntegerField()),
                ('rubric_version', models.CharField(max_length=50)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('factual', 'Factual Information'), ('negative_factual', 'Negative Factual'), ('inference', 'Inference'), ('vocabulary', 'Vocabulary in Context'), ('insert_sentence', 'Insert Sentence'), ('summary', 'Summary'), ('table', 'Table Completion')], max_length=30)),
                ('correct_answer', models.TextField()),
                ('score', models.IntegerField(default=1)),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='team14.passage')),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('exam', 'Exam Mode'), ('practice', 'Practice Mode')], max_length=10)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('total_score', models.IntegerField(blank=True, null=True)),
                ('scaled_score', models.FloatField(blank=True, null=True)),
                ('exam_version', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField()),
                ('response_time', models.FloatField(help_text='Time in seconds')),
                ('changed_count', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team14.question')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='team14.option')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='team14.usersession')),
            ],
        ),
        migrations.CreateModel(
            name='SkillScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_type', models.CharField(choices=[('main_idea', 'Main Idea'), ('supporting_detail', 'Supporting Detail'), ('inference', 'Inference'), ('vocabulary', 'Vocabulary'), ('cohesion', 'Cohesion'), ('organization', 'Organization')], max_length=30)),
                ('score', models.FloatField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_scores', to='team14.usersession')),
            ],
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='team14.question'),
        ),
        migrations.CreateModel(
            name='AntiCheatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('focus_lost', 'Focus Lost'), ('answer_changed', 'Answer Changed'), ('long_idle', 'Long Idle')], max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheat_logs', to='team14.usersession')),
            ],
        ),
    ]
