# Generated by Django 4.2.27 on 2026-02-10 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("team14", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersession",
            name="passage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessions",
                to="team14.passage",
            ),
        ),
    ]
