# Generated by Django 4.2.27 on 2026-02-10 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team14", "0002_usersession_passage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersession",
            name="user",
        ),
        migrations.AddField(
            model_name="usersession",
            name="user_id",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
