# Generated by Django 4.2.27 on 2026-02-10 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("team14", "0003_remove_usersession_user_usersession_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersession",
            name="user_id",
            field=models.CharField(max_length=36),
        ),
    ]
