# Generated by Django 4.2.27 on 2026-02-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team14', '0004_alter_usersession_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='exam_duration',
            field=models.IntegerField(blank=True, help_text='Exam duration in seconds', null=True),
        ),
    ]
