# Generated by Django 4.2.27 on 2026-02-12 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team8', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('word', models.CharField(max_length=100)),
                ('ipa_pronunciation', models.CharField(blank=True, max_length=100)),
                ('definition', models.TextField(blank=True)),
                ('synonyms', models.TextField(blank=True)),
                ('antonyms', models.TextField(blank=True)),
                ('collocations', models.TextField(blank=True)),
                ('example_sentences', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('user_id', 'word')},
            },
        ),
    ]
